# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 48641b600e4b83f80eec87ac0bb6984baa9750cf6863789a69059f70da80ca4e5ed18c30e98bd0b8a5955c40ab96937ed877b2c393da2d6a729098599194b041

test:
  secret_key_base: 01e9ef2afba939c548389821849263b6d71317d94eadb3194df40a9e6ba59bdf40eab1b49917c3b195306f217a367ab7286b3d629d6c7f1c361416d11f86a47c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
